/**
 * Context compression — summarize old history to stay within token limits.
 *
 * Strategy:
 * - Estimate tokens via string length / 4 (good enough without tiktoken)
 * - When history exceeds threshold, keep recent messages intact
 * - Summarize older messages into a single "[Context Summary]" message
 * - Summary is generated by the LLM itself via a cache-safe forked call:
 *   the request shares the same system prompt + the same prefix of history
 *   as the main session, with one extra user turn appended asking for a
 *   summary. This way the provider's prefix cache hits all the way up to
 *   the summarize instruction — only the last turn is fresh tokens.
 */

import type { Message, ContentBlock, GatewayConfig } from '../types.js'
import { buildSystemMessage, historyToOpenAI } from './openai-format.js'

// ─── Token estimation ────────────────────────────────────────────────────────

function estimateTokens(msg: Message): number {
  if (typeof msg.content === 'string') {
    return Math.ceil(msg.content.length / 4)
  }
  const blocks = msg.content as ContentBlock[]
  let chars = 0
  for (const b of blocks) {
    if (b.type === 'text') chars += b.text.length
    else if (b.type === 'tool_use') chars += b.name.length + JSON.stringify(b.input).length
    else if (b.type === 'tool_result') chars += b.content.length
  }
  return Math.ceil(chars / 4)
}

export function estimateHistoryTokens(history: Message[]): number {
  return history.reduce((sum, m) => sum + estimateTokens(m), 0)
}

// ─── Find safe split point ──────────────────────────────────────────────────

/**
 * Find where to split history for compression.
 * Returns the index that divides [old (to compress)] and [recent (to keep)].
 *
 * Rules:
 * - Keep at least `keepRecent` messages at the end
 * - Never split in the middle of a tool_use → tool_result pair
 *   (assistant with tool_use must be followed by user with tool_result)
 */
function findSplitPoint(history: Message[], keepRecent: number): number {
  const candidateIdx = history.length - keepRecent
  if (candidateIdx <= 1) return -1 // Nothing worth compressing

  // Walk backwards from candidate to find a clean boundary
  // A clean boundary is after a user text message or after a complete tool cycle
  for (let i = candidateIdx; i >= 1; i--) {
    const msg = history[i]
    // Good split: right before a user text message
    if (msg.role === 'user' && typeof msg.content === 'string') {
      return i
    }
  }

  return candidateIdx
}

// ─── Extract text for summarization ──────────────────────────────────────────

function historyToText(history: Message[]): string {
  const lines: string[] = []
  for (const msg of history) {
    if (typeof msg.content === 'string') {
      lines.push(`[${msg.role}]: ${msg.content}`)
    } else {
      const blocks = msg.content as ContentBlock[]
      for (const b of blocks) {
        if (b.type === 'text') {
          lines.push(`[${msg.role}]: ${b.text}`)
        } else if (b.type === 'tool_use') {
          lines.push(`[tool_use]: ${b.name}(${JSON.stringify(b.input).slice(0, 200)})`)
        } else if (b.type === 'tool_result') {
          const preview = b.content.slice(0, 300)
          lines.push(`[tool_result]: ${preview}${b.content.length > 300 ? '…' : ''}`)
        }
      }
    }
  }
  return lines.join('\n')
}

// ─── Compression ────────────────────────────────────────────────────────────

const COMPRESSION_THRESHOLD = Number(process.env.DUCK_COMPRESS_THRESHOLD ?? 30_000)
const KEEP_RECENT = Number(process.env.DUCK_COMPRESS_KEEP_RECENT ?? 6)

export interface CompressResult {
  compressed: boolean
  oldTokens: number
  newTokens: number
}

/**
 * Check if compression is needed and perform it.
 * Mutates the history array in place.
 *
 * `projectContext` is forwarded into the summary call so the request shares
 * the exact same system prompt (byte-identical) with the main session. That
 * preserves the provider's prefix-cache hit on the system bytes.
 */
export async function compressIfNeeded(
  history: Message[],
  config: GatewayConfig,
  projectContext: string,
): Promise<CompressResult> {
  const totalTokens = estimateHistoryTokens(history)

  if (totalTokens < COMPRESSION_THRESHOLD) {
    return { compressed: false, oldTokens: totalTokens, newTokens: totalTokens }
  }

  const splitIdx = findSplitPoint(history, KEEP_RECENT)
  if (splitIdx <= 0) {
    return { compressed: false, oldTokens: totalTokens, newTokens: totalTokens }
  }

  const oldMessages = history.slice(0, splitIdx)
  const recentMessages = history.slice(splitIdx)

  // Cache-safe fork: hand the model the live message objects (not a flattened
  // text dump) so the request prefix matches what the main session sent in
  // prior turns. Fallback path inside generateSummary uses the flat text only
  // if the LLM call fails.
  const summary = await generateSummary(oldMessages, config, projectContext)

  // Replace history: summary + recent messages
  const summaryMessage: Message = {
    role: 'user',
    content: `[Context Summary — earlier conversation compressed]\n${summary}`,
  }

  // Mutate in place
  history.length = 0
  history.push(summaryMessage, ...recentMessages)

  const newTokens = estimateHistoryTokens(history)
  return { compressed: true, oldTokens: totalTokens, newTokens }
}

// ─── Summary generation ─────────────────────────────────────────────────────

const SUMMARY_INSTRUCTION =
  'The conversation above is approaching the context limit and will be ' +
  'compressed. Produce a bullet-point summary of everything above, under ' +
  '200 words. No markdown headers, no commentary, no repetition. Cover: ' +
  'what the user asked for, files read/created/edited (paths only), key ' +
  'decisions and errors resolved, current state and pending items.'

async function generateSummary(
  oldMessages: Message[],
  config: GatewayConfig,
  projectContext: string,
): Promise<string> {
  // Build the request as a true prefix of the main session: same system
  // message, same OpenAI-shape converted history, then one new user turn
  // asking for a summary. Provider prefix caching keys on the message-byte
  // sequence, so this maximizes cache reuse on the summary call.
  const systemMessage = buildSystemMessage(config, projectContext)
  const messages = [
    systemMessage,
    ...historyToOpenAI(oldMessages),
    { role: 'user', content: SUMMARY_INSTRUCTION },
  ]

  const response = await fetch(`${config.baseUrl}/v1/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      model: config.model,
      messages,
      max_tokens: 1024,
      stream: false,
      // Deliberately omit `tools` and `tool_choice`. We want a pure text
      // response; sending tools risks the model emitting tool_calls instead
      // of summary text. Omitting tools also keeps the request shape
      // distinct from a normal main-session call so debug logs are obvious.
    }),
  })

  if (!response.ok) {
    // Fallback: flat-text dump of old messages (legacy path) so the system
    // still degrades gracefully if the API rejects the forked request.
    const flat = historyToText(oldMessages).slice(0, 2000)
    return `[Auto-summary failed — using truncated history]\n${flat}`
  }

  const data = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>
  }

  let summary = data.choices?.[0]?.message?.content ?? '[Summary generation returned empty]'

  // Strip <think>...</think> blocks from summary (MiniMax includes them
  // even in non-streaming responses — see 踩坑记录 坑 12).
  summary = summary.replace(/<think>[\s\S]*?<\/think>/g, '').trim()

  return summary
}
