/**
 * Context compression — summarize old history to stay within token limits.
 *
 * Strategy:
 * - Estimate tokens via string length / 4 (good enough without tiktoken)
 * - When history exceeds threshold, keep recent messages intact
 * - Summarize older messages into a single "[Context Summary]" message
 * - Summary is generated by the LLM itself (non-streaming call)
 */

import type { Message, ContentBlock, GatewayConfig } from '../types.js'

// ─── Token estimation ────────────────────────────────────────────────────────

function estimateTokens(msg: Message): number {
  if (typeof msg.content === 'string') {
    return Math.ceil(msg.content.length / 4)
  }
  const blocks = msg.content as ContentBlock[]
  let chars = 0
  for (const b of blocks) {
    if (b.type === 'text') chars += b.text.length
    else if (b.type === 'tool_use') chars += b.name.length + JSON.stringify(b.input).length
    else if (b.type === 'tool_result') chars += b.content.length
  }
  return Math.ceil(chars / 4)
}

export function estimateHistoryTokens(history: Message[]): number {
  return history.reduce((sum, m) => sum + estimateTokens(m), 0)
}

// ─── Find safe split point ──────────────────────────────────────────────────

/**
 * Find where to split history for compression.
 * Returns the index that divides [old (to compress)] and [recent (to keep)].
 *
 * Rules:
 * - Keep at least `keepRecent` messages at the end
 * - Never split in the middle of a tool_use → tool_result pair
 *   (assistant with tool_use must be followed by user with tool_result)
 */
function findSplitPoint(history: Message[], keepRecent: number): number {
  const candidateIdx = history.length - keepRecent
  if (candidateIdx <= 1) return -1 // Nothing worth compressing

  // Walk backwards from candidate to find a clean boundary
  // A clean boundary is after a user text message or after a complete tool cycle
  for (let i = candidateIdx; i >= 1; i--) {
    const msg = history[i]
    // Good split: right before a user text message
    if (msg.role === 'user' && typeof msg.content === 'string') {
      return i
    }
  }

  return candidateIdx
}

// ─── Extract text for summarization ──────────────────────────────────────────

function historyToText(history: Message[]): string {
  const lines: string[] = []
  for (const msg of history) {
    if (typeof msg.content === 'string') {
      lines.push(`[${msg.role}]: ${msg.content}`)
    } else {
      const blocks = msg.content as ContentBlock[]
      for (const b of blocks) {
        if (b.type === 'text') {
          lines.push(`[${msg.role}]: ${b.text}`)
        } else if (b.type === 'tool_use') {
          lines.push(`[tool_use]: ${b.name}(${JSON.stringify(b.input).slice(0, 200)})`)
        } else if (b.type === 'tool_result') {
          const preview = b.content.slice(0, 300)
          lines.push(`[tool_result]: ${preview}${b.content.length > 300 ? '…' : ''}`)
        }
      }
    }
  }
  return lines.join('\n')
}

// ─── Compression ────────────────────────────────────────────────────────────

const COMPRESSION_THRESHOLD = Number(process.env.DUCK_COMPRESS_THRESHOLD ?? 30_000)
const KEEP_RECENT = Number(process.env.DUCK_COMPRESS_KEEP_RECENT ?? 6)

export interface CompressResult {
  compressed: boolean
  oldTokens: number
  newTokens: number
}

/**
 * Check if compression is needed and perform it.
 * Mutates the history array in place.
 */
export async function compressIfNeeded(
  history: Message[],
  config: GatewayConfig,
): Promise<CompressResult> {
  const totalTokens = estimateHistoryTokens(history)

  if (totalTokens < COMPRESSION_THRESHOLD) {
    return { compressed: false, oldTokens: totalTokens, newTokens: totalTokens }
  }

  const splitIdx = findSplitPoint(history, KEEP_RECENT)
  if (splitIdx <= 0) {
    return { compressed: false, oldTokens: totalTokens, newTokens: totalTokens }
  }

  const oldMessages = history.slice(0, splitIdx)
  const recentMessages = history.slice(splitIdx)
  const oldText = historyToText(oldMessages)

  // Call LLM to generate summary (non-streaming)
  const summary = await generateSummary(oldText, config)

  // Replace history: summary + recent messages
  const summaryMessage: Message = {
    role: 'user',
    content: `[Context Summary — earlier conversation compressed]\n${summary}`,
  }

  // Mutate in place
  history.length = 0
  history.push(summaryMessage, ...recentMessages)

  const newTokens = estimateHistoryTokens(history)
  return { compressed: true, oldTokens: totalTokens, newTokens }
}

// ─── Summary generation ─────────────────────────────────────────────────────

async function generateSummary(
  conversationText: string,
  config: GatewayConfig,
): Promise<string> {
  // Truncate if the old conversation is extremely long
  const maxInput = 15_000 * 4 // ~15k tokens worth of chars
  const truncated = conversationText.length > maxInput
    ? conversationText.slice(0, maxInput) + '\n[…truncated]'
    : conversationText

  const response = await fetch(
    `${config.baseUrl}/v1/chat/completions`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${config.apiKey}`,
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          {
            role: 'system',
            content: `You are a conversation summarizer. Output ONLY a bullet-point summary, no commentary. Keep under 200 words. Include:
- What the user asked for
- Files read/created/edited (paths only)
- Key decisions and errors resolved
- Current state and pending items
Do not use markdown headers. Do not repeat yourself.`,
          },
          {
            role: 'user',
            content: `Summarize this conversation:\n\n${truncated}`,
          },
        ],
        max_tokens: 1024,
        stream: false,
      }),
    },
  )

  if (!response.ok) {
    // Fallback: simple truncation if LLM fails
    return `[Auto-summary failed — using truncated history]\n${conversationText.slice(0, 2000)}`
  }

  const data = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>
  }

  let summary = data.choices?.[0]?.message?.content ?? '[Summary generation returned empty]'

  // Strip <think>...</think> blocks from summary (MiniMax includes them)
  summary = summary.replace(/<think>[\s\S]*?<\/think>/g, '').trim()

  return summary
}
